x-database: &database
  image: postgres:15.7-bookworm
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
  healthcheck:
    test: ["CMD-SHELL", "pg_isready"]
    interval: 5s
    timeout: 5s
    retries: 20
    start_period: 10s

services:
  database: 
    <<: *database
    container_name: expense-tracker-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  database-test:
    <<: *database
    container_name: expense-tracker-db-test
    restart: on-failure:5
    ports:
      - 6000:5432

volumes:
  pgdata: