name: "Test"
on:
  push:
    branches-ignore:
      - $default-branch

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up TypeScript
        uses: actions/setup-node@v2
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test:unit
