name: "Vulnerabilities Checker"
on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up TypeScript
        uses: actions/setup-node@v2
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm install
      - name: Test dependencies for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: npm run scan-dependencies
      # - name: Test code for vulnerabilities
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #     SNYK_ORG: ${{ secrets.SNYK_ORG }}
      #     CSRF_TOKEN_SECRET: ${{ secrets.CSRF_TOKEN_SECRET }}
        # run: npm run scan-code
      - name: Monitor dependencies for vulnerabilities
        run: npm run monitor-vulnerabilities